[package]
name = "hyperx-hid"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hyperx-core = { path = "../hyperx-core" }
hyperx-protocol = { path = "../hyperx-protocol" }
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
hidapi = { version = "=2.6.1", default-features = false, features = ["windows-native"] }

[target.'cfg(target_os = "linux")'.dependencies]
hidapi = { version = "=2.6.1", default-features = false, features = ["linux-static-hidraw"] }

[target.'cfg(target_os = "macos")'.dependencies]
hidapi = { version = "=2.6.1", default-features = false, features = ["macos-shared-device"] }
