[package]
name = "hyperx-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
hyperx-core = { path = "../hyperx-core" }
hyperx-devices = { path = "../hyperx-devices" }
hyperx-hid = { path = "../hyperx-hid" }
hyperx-protocol = { path = "../hyperx-protocol" }
tracing.workspace = true
tracing-subscriber.workspace = true
