[package]
name = "hyperx-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
hyperx-core = { path = "../hyperx-core" }
hyperx-devices = { path = "../hyperx-devices" }
serde.workspace = true
toml.workspace = true
